// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChroBgVAl7h4_ZbNHDvOg8hGeuljjxcIA',
    appId: '1:977679450418:web:e26d624807373bb744972b',
    messagingSenderId: '977679450418',
    projectId: 'hazri-e3bec',
    authDomain: 'hazri-e3bec.firebaseapp.com',
    storageBucket: 'hazri-e3bec.firebasestorage.app',
    measurementId: 'G-WXX7FTKLEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNcbSJ_p9xn8qKfz9uk4M3eWohwOGpf4',
    appId: '1:977679450418:android:ace7cce0f84f7e7644972b',
    messagingSenderId: '977679450418',
    projectId: 'hazri-e3bec',
    storageBucket: 'hazri-e3bec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ZaSeUhGCwnJykplsF3uNjnjY_2l_7B8',
    appId: '1:977679450418:ios:2a489bf988a8656844972b',
    messagingSenderId: '977679450418',
    projectId: 'hazri-e3bec',
    storageBucket: 'hazri-e3bec.firebasestorage.app',
    iosBundleId: 'com.example.attandenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChroBgVAl7h4_ZbNHDvOg8hGeuljjxcIA',
    appId: '1:977679450418:web:724edcf2125c5d8644972b',
    messagingSenderId: '977679450418',
    projectId: 'hazri-e3bec',
    authDomain: 'hazri-e3bec.firebaseapp.com',
    storageBucket: 'hazri-e3bec.firebasestorage.app',
    measurementId: 'G-H9PJ4HDK32',
  );
}
